
name: Build and Package MSI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build release binary
        run: cargo build --release --manifest-path waagent-poc/Cargo.toml

      - name: Generate and build MSI with cargo wix
        run: |
          cd waagent-poc
          cargo wix -p waagent-rs-poc --nocapture
          cd ..
          # Move MSI to root for artifact upload
          move waagent-poc\*.msi .

      - name: Inspect MSI contents with dark.exe
        run: |
          $msiFiles = Get-ChildItem -Path . -Filter 'waagent-*.msi'
          foreach ($file in $msiFiles) {
              dark.exe $file.FullName -x msi_contents
              Get-ChildItem -Recurse msi_contents | ForEach-Object { Write-Host $_.FullName }
          }

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: waagent-rs-msi
          path: waagent-poc/waagent-rs-poc-*.msi

  release:
    needs: build-msi
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.msi
