name: Build Debian Packages

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Replace sources.list for multi-arch
        run: |
          sudo dpkg --add-architecture arm64
          sudo tee /etc/apt/sources.d/sources.list > /dev/null <<EOF
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble-security main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse

          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse
          EOF
          sudo apt update

      - name: Add target and deps
        run: |
          sudo apt install libssl-dev gcc-aarch64-linux-gnu libssl-dev:arm64
          rustup target add ${{ matrix.target }}

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Debian package
        run: |
          cargo build --release --target ${{ matrix.target }}
          cargo deb --target ${{ matrix.target }}

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-${{ matrix.target }}
          path: target/${{ matrix.target }}/debian/*.deb

  release:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.deb
