name: Build and Release waagent-rs RPM

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-rpm-multi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [oraclelinux:8, oraclelinux:9, mcr.microsoft.com/azurelinux/base/core:3.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build rpm
        run: |
          docker run --rm  \
            -v ${{ github.workspace }}:/src -w /src ${{ matrix.distro }} \
            bash -c " 
              if [ -x /usr/bin/tdnf ]; then export TOOL=tdnf
              elif [ -x /usr/bin/dnf ]; then export TOOL=dnf
              elif [ -x /usr/bin/zypper ]; then export TOOL=zypper;
              else echo 'No tool found'; exit 0; fi
              if grep -q ubi /etc/os-release; then
                 dnf config-manager --set-enabled codeready-builder-for-rhel-8-x86_64-rpms
              fi
              \$TOOL -y update
              \$TOOL -y install rpmdevtools gcc ca-certificates pkg-config openssl-devel kernel-headers binutils glibc-devel
              rpmdev-setuptree
              cp rpm/*.spec ~/rpmbuild/SPECS/
              spectool -C ~/rpmbuild/SOURCES/ -g ~/rpmbuild/SPECS/waagent-rs.spec
              rpmbuild -ba --nodebuginfo ~/rpmbuild/SPECS/*.spec
              find ~/rpmbuild/RPMS -name '*.rpm' -exec cp -v {} /src/ \;
            "

      - name: Set RPM path output
        id: find_rpm
        run: |
              ls -lh /src/
              ls -lh /
              RPM_PATH=$(find /src -name "*.rpm" | grep -v debuginfo | head -n 1)
              echo "rpm_path=$RPM_PATH" | tee -a $GITHUB_OUTPUT

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: waagent-rs-${{ matrix.arch }}
          path: ${{ steps.find_rpm.outputs.rpm_path }}

  release:
    needs: build-rpm-multi
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.rpm

#Change log
#    Wed Aug 27 2025 Mitch Tenorio (mitenori@microsoft.com)
#
