name: Build and Release waagent-rs RPM

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-rpm-multi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [oraclelinux:8, oraclelinux:9, registry.access.redhat.com/ubi8, mcr.microsoft.com/azurelinux/base/core:3.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          docker run --rm  \
            -v ${{ github.workspace }}:/src -w /src ${{ matrix.distro }} \
            bash -c " 
              if which tdnf; then export TOOL=tdnf; elif which dnf; then export TOOL=dnf; elif which zypper; then export TOOL=zypper; fi
              $TOOL -y update
              $TOOL -y install rpmdevtools gcc ca-certificates pkg-config openssl-devel kernel-headers binutils glibc-devel
            "

      - name: Prepare RPM build environment
        run: |
          rpmdev-setuptree
          cp rpm/*.spec ~/rpmbuild/SPECS/
          spectool -C ~/rpmbuild/SOURCES/ -g ~/rpmbuild/SPECS/waagent-rs.spec

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/*.spec --target ${{ matrix.rpm_arch }}

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS -name "*.rpm" | grep -v debuginfo | head -n 1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: waagent-rs-${{ matrix.arch }}
          path: ${{ steps.find_rpm.outputs.rpm_path }}

  release:
    needs: build-rpm-multi
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.rpm

#Change log
#    Wed Aug 27 2025 Mitch Tenorio (mitenori@microsoft.com)
#
